kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: common-webui
subjects:
- kind: ServiceAccount
  name: common-webui
roleRef:
  kind: Role
  name: common-webui
  apiGroup: rbac.authorization.k8s.io
